spring.application.name=Task-Management-System

spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManagement
spring.datasource.password=Sidd@2004
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=dGhpcy1pcy1hLXNlY3VyZS0yNTYtYml0LWJhc2U2NC1lbmNvZGVkLXNlY3JldA==
app.jwt.expiration-ms=172800000